# Generated by Django 4.2.4 on 2023-11-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_estudiante_options_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre:')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='Image:')),
            ],
        ),
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name_plural': 'Comisiones'},
        ),
    ]
