# Generated by Django 4.2.4 on 2023-10-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('apellido', models.TextField(verbose_name='Apellido')),
                ('dni', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='DNI')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('apodo', models.CharField(max_length=250, verbose_name='Apodo')),
            ],
        ),
    ]
